version: 2
jobs:

  qa:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Run linters
          command: yarn lint
      - run:
          name: Compile the code
          command: yarn compile
      - run:
          name: Run tests and calculate code coverage
          command: yarn coverage
      - run:
          name: Publish code coverage report
          command: yarn publish-coverage

  publish-version-website:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install staticdeploy cli
          command: |
            yarn global add @staticdeploy/cli
            echo 'export PATH=$PATH:$(yarn global bin)' >> $BASH_ENV
      - run:
          name: Compile version website
          command: WEBSITE_BASE=/_/${CIRCLE_TAG:-$CIRCLE_BRANCH}/ yarn docs:build
      - run:
          name: Create version website bundle
          command: staticdeploy bundle
      - run:
          name: Deploy version website
          command: staticdeploy deploy

  publish-latest-website:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Install staticdeploy cli
          command: |
            yarn global add @staticdeploy/cli
            echo 'export PATH=$PATH:$(yarn global bin)' >> $BASH_ENV
      - run:
          name: Compile latest website
          command: WEBSITE_BASE=/ yarn docs:build
      - run:
          name: Create latest website bundle
          command: DEPLOY_LATEST_WEBSITE=true staticdeploy bundle
      - run:
          name: Deploy latest website
          command: DEPLOY_LATEST_WEBSITE=true staticdeploy deploy

  npm-publish:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile the code
          command: yarn lint
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

workflows:
  version: 2
  qa-npm:
    jobs:
      - qa:
          # Run for all branches and all tags
          filters:
            tags:
              only: /.*/
      - publish-version-website:
          requires:
            - qa
          # Run for all branches and all tags
          filters:
            tags:
              only: /.*/
      - publish-latest-website:
          requires:
            - qa
          # Run only for tags starting with a v, don't run for branches
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - npm-publish:
          requires:
            - qa
          # Run only for tags starting with a v, don't run for branches
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
